### ISSUE TITLE
"関数の読み込み"で使用している関数について

### ISSUE THREAD

**Issue by mofumofu-inu** [mizuhirosuzuki/keisemi_io#2]
鈴木様

お世話になっております。

Julia版コードを拝見させていただき、以下の点について御質問させていただければと思います。

各回の最初で、"関数の読み込み"があるかと思いますが、ここで読み込まれている関数は、どこかに公開されていますでしょうか？

お手隙の際に御返信いただけますと幸いです。

**Comment by mizuhirosuzuki** [comment]
ご連絡いただき、ありがとうございます。
各回で読み込まれている関数は[こちら](https://github.com/mizuhirosuzuki/keisemi_io/tree/master/functions)で見つけられます。
もし問題がありましたら連絡頂けますと幸いです。

**Comment by mofumofu-inu** [comment]
早速の御回答ありがとうございます。

"code"に気づかず、お手数をおかけしてすみませんでした。確認させていただきます。

また不明点等がありましたら、御質問させていただけますと幸いです。

引き続き、何卒よろしくお願いします。
